### ISSUE TITLE
Download packagee link in the description not working

### ISSUE THREAD

**Issue by vbarzana** [hipay/hipay-professional-sdk-prestashop#6]
Hi guys,
The link: "Download the package" in the Readme.md does not work.

![image](https://user-images.githubusercontent.com/3055285/54591621-4bfa6780-4a33-11e9-9a50-6e9e61d09f5c.png)

Thank you for looking into it.
Victor

**Comment by jprotin** [comment]
Hi @vbarzana 

Many thanks. it's fixed.

**Comment by vbarzana** [comment]
Wow, that was fast, thank you Mr. Protin.
Regards,
Victor
